language: java
# Run on OSX and Linux
matrix:
  include:
    - os: linux
      jdk: oraclejdk7
    - os: osx
      #osx_image: beta-xcode6.1
# Run Integration tests
script: "mvn test && mvn clean verify"
before_install:
  - wget https://dl.dropboxusercontent.com/u/7897865/apache-maven-3.3.9.zip
  - unzip -qq apache-maven-3.3.9.zip
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH
